name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: # Python executables might differ depending on running platform
          # On Ubuntu 18.04, default python3 is 3.6 < 3.7, so we'll need to call python modules through python3.7 so the correct version
          # will be executed
        - name: "ubuntu-18.04"
          python: "python3.7"
          pip: "python3.7 -m pip"
        - name: "ubuntu-20.04"
          python: "python3"
          pip: "pip3"
          # On Windows, build operation uses tmp virtual envs which don't have a python3.exe file, and as build use the invoked interpreter
          # to select command to run inside these virtual envs, we need to call for just python running at least 3.7 on this hosted runner
        - name: "windows-latest"
          python: "python"
          pip: "pip"
    runs-on: ${{matrix.platform.name}}
    name: ${{matrix.platform.name}} build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upgrade to Python 3.7 if required # Default python3 for Ubuntu 18.04 is 3.6
        if: matrix.platform.name == 'ubuntu-18.04'
        run: sudo apt-get install -y python3.7 python3.7-venv

      - name: Upgrade pip if required # On Ubuntu 18.04, pip default version is outdated and doesn't support setup.cfg
        if: matrix.platform.name == 'ubuntu-18.04'
        run: ${{matrix.platform.pip}} install pip

      - name: Install unit testing framework and build command (dev only, not in requirements)
        run: ${{matrix.platform.pip}} install pytest-xdist build

      - name: Generate distribution packages
        run: ${{matrix.platform.python}} -m build

      - name: Install local package
        run: ${{matrix.platform.pip}} install .

      - name: Run tests
        run: pytest -n auto tests
  publish: # If pushed on stable branch, then a new release has been done and must be published if all tests passed successfully
    if: endsWith(github.ref, 'stable') # Expects ref to be ref/heads/stable
    needs: build
    runs-on: ubuntu-latest
    name: Publish if it is a new release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate distribution packages
        run: python3 -m build

      - name: Publish built packaages
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{secrets.PYPI_API_TOKEN}}
